uciblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

uciblog/blog_posts/views.py
from flask import render_template, url_for, request, redirect, Blueprint
from flask_login import current_user, login_required
from uciblog import db
from uciblog.models import BlogPost
from uciblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)

@blog_posts.route('/create', methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title = form.title.data,
                             text = form.text.data,
                             user_id = current_user.id
                             )
        db.session.add(blog_post)
        db.session.commit()
        return redirect(url_for('core.index'))
    return render_template('create_post.html',form=form)

@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title,
                            date=blog_post.date, post=blog_post)

@blog_posts.route('/<int:blog_post_id>/update', methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():

        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html',form=form)

@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()

    return redirect(url_for('core.index'))

uciblog/core/views.py
from flask import render_template, request, Blueprint
from uciblog.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('index.html', blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

uciblog/users/views.py
from flask import render_template,url_for,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from uciblog import db
from uciblog.models import User, BlogPost
from uciblog.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from uciblog.users.picture_handler import add_profile_pic

users = Blueprint('users',__name__)

@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('register.html',form=form)

@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


@users.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()

        return redirect(url_for('users.account'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)

@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page',1,type='int')
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=9)
    return render_template('user_blog_posts.html',blog_posts=blog_posts, user=user)

uciblog/templates/account.html
{% extends "base.html" %}
{% block content %}
  <div class="container-fluid text-sm-center p-5 bg-light">
    <h1 class="display-2 pb-4">Your Profile</h1>
    <img src="{{url_for('static', filename='profile_pics/'+current_user.profile_image)}}" alt="">
  </div>
  <div class="container-sm">
    <form method="post" action="" enctype="multipart/form-data">
      {{form.hidden_tag()}}
      <div class="mb-3">
        {{form.username.label(class="form-label")}}{{form.username(class="form-control")}}
      </div>
      <div class="mb-3">
        {{form.email.label(class="form-label")}}{{form.email(class="form-control")}}
      </div>
      <div class="mb-3">
        {{form.picture.label(class="form-label")}}{{form.picture(class="form-control")}}
      </div>
      <div class="mb-3">
        {{form.submit(class="btn btn-primary")}}
      </div>
    </form>

  </div>
{% endblock %}

uciblog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary bg-opacity-75">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">UCIBlog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{{url_for('core.index')}}">Home</a>
            <a class="nav-link" href="{{url_for('core.info')}}">About</a>
            {% if current_user.is_authenticated %}
            <a class="nav-link" href="{{url_for('users.logout')}}">Log Out</a>
            <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
            <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">Create Post</a>
            {% else %}
            <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
            <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>

uciblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
  <div class="container-med mt-4 bg-warning bg-opacity-50">
    <h1 class="display-2 p-3 text-sm-center">{{post.title}}</h1>
    <div class="container-fluid">
      <h4 class="p-2">Written by: {{post.author.username}}</h2>
      <h4 class="p-2">Published: {{post.date.strftime('%B %d, %Y')}}</h3>
      <p class="p-2">{{post.text}}</p>
    </div>

    {% if post.author == current_user %}
    <div class="text-sm-center p-3">
      <a class="btn btn-primary" href="{{url_for('blog_posts.update', blog_post_id = post.id)}}" role="button">Update</a>
      <button class="btn btn-primary" type="button" name="button" data-bs-toggle='modal' data-bs-target='#del_modal'>Delete</button>
    </div>
    {% endif %}
  </div>
<div class="modal" tabindex="-1" id="del_modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to the delete the post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <form class="" action="{{url_for('blog_posts.delete_post', blog_post_id=post.id)}}" method="post">
              <input class="btn btn-primary" type="submit" name="" value="Delete">
          </form>
        </div>
      </div>
    </div>
</div>

{% endblock %}

uciblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
  <div class="container-sm mt-5 bg-light">
    <form method="post">
      {{form.hidden_tag()}}
      <div class="mb-3">
        {{form.title.label(class="form-label")}}{{form.title(class="form-control")}}
      </div>
      <div class="mb-3">
        {{form.text.label(class="form-label")}}{{form.text(class="form-control")}}
      </div>
      <div class="mb-3">
        {{form.submit(class="btn btn-primary")}}
      </div>
    </form>
  </div>
{% endblock %}

uciblog/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="container-med text-sm-center p-5">
    <h1 class="display-2">UCI Blog</h1>
  </div>
  <div class="container-fluid row row-cols-1 row-cols-md-3 g-4">
    {% for post in blog_posts.items %}
    <div class="col">
      <div class="card h--100 text-center text-bg-warning mb-3 bg-opacity-50">
        <div class="card-body">
          <h5 class="card-title">{{post.title}}</h5>
          <a class="link-dark" href="{{url_for('users.user_posts',username=post.author.username)}}">Written By: {{post.author.username}}</a>
          <p class="text-muted">Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
          <a href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}" class="btn btn-primary">Read Blog Post</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class="page-item disbaled">
          <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
        </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>
{% endblock %}

uciblog/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="container-fluid text-sm-center p-5 bg-light">
    <h1 class="display-2">Info about our blog</h1>
    <p class="p-3 lead">A blog page where UCI students can blog about their experiences at UCI.</p>
  </div>
{% endblock %}

uciblog/templates/login.html
{% extends "base.html" %}
{% block content %}
  <form method="post" class="container-sm mt-5">
    {{form.hidden_tag()}}
    <div class="mb-3">
      {{form.email.label(class="form-label")}}{{form.email(class="form-control")}}
    </div>
    <div class="mb-3">
      {{form.password.label(class="form-label")}}{{form.password(class="form-control")}}
    </div>
    <div class="mb-3">
      {{form.submit(class="btn btn-primary")}}
    </div>
  </form>
{% endblock %}

uciblog/templates/register.html
{% extends "base.html" %}
{% block content %}
  <form method="post" class="container-sm mt-5">
    {{form.hidden_tag()}}
    <div class="mb-3">
      {{form.email.label(class="form-label")}}{{form.email(class="form-control")}}
    </div>
    <div class="mb-3">
      {{form.username.label(class="form-label")}}{{form.username(class="form-control")}}
    </div>
    <div class="mb-3">
      {{form.password.label(class="form-label")}}{{form.password(class="form-control")}}
    </div>
    <div class="mb-3">
      {{form.pass_confirm.label(class="form-label")}}{{form.pass_confirm(class="form-control")}}
    </div>
    <div class="mb-3">
      {{form.submit(class="btn btn-primary")}}
    </div>
  </form>
{% endblock %}

uciblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
  <div class="container-fluid text-sm-center p-5 bg-light">
    <h1 class="display-2">{{user.username}}'s blog Posts</h1>
    <img class="pb-4" src="{{url_for('static', filename='profile_pics/'+user.profile_image)}}" alt="">
    <div class="container-fluid row row-cols-1 row-cols-md-3 g-4">
      {% for post in blog_posts.items %}
        <div class="col">
          <div class="card h--100 text-center text-bg-warning mb-3 bg-opacity-50">
            <div class="card-body">
              <h5 class="card-title">{{post.title}}</h5>
              <a class="link-dark" href="{{url_for('users.user_posts',username=post.author.username)}}">Written By: {{post.author.username}}</a>
              <p class='text-muted'>Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
              <a href="{{url_for('blog_posts.blog_post', blog_post_id=post.id)}}" class="btn btn-primary">Read Blog Post</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
      {% if blog_posts.page == page_num %}
      <li class="page-item disbaled">
        <a class="page-link" href="{{url_for('users.user_posts', username=user.username,page=page_num)}}">{{ page_num }}</a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{url_for('users.user_posts', username=user.username,page=page_num)}}">{{ page_num }}</a>
      </li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>


{% endblock %}